version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: grad-hub-tracker-backend-db
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  nestjs:
    build: 
      context: ./grad-hub-tracker-backend
      dockerfile: Dockerfile
      network: host
    container_name: grad-hub-tracker-backend
    ports:
      - "2053:2053"
    networks:
      - app-network
    env_file:
      - .env
    depends_on:
      - postgres
    tty: true 
    stdin_open: true

  react:
    build:
      context: ./grad-hub-tracker-main
      dockerfile: Dockerfile
      network: host
    container_name: grad-hub-tracker-frontend
    ports:
      - "2082:2082"
    networks:
      - app-network
    env_file:
      - .env
    tty: true 
    stdin_open: true

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: